stages:
  - test

variables:
  GIT_DEPTH: '3'

cache:
  key: '${CI_JOB_NAME}'
  paths:
    - node_modules/

linux-test:
  stage: test
  image: node:12
  script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn install --frozen-lockfile
    - yarn test
    - yarn lint
  tags:
    - linux-docker
